"""user updated

Revision ID: 0bcc8350358b
Revises: cb7714d6afe5
Create Date: 2024-04-06 14:16:34.543598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcc8350358b'
down_revision = 'cb7714d6afe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('age')
        batch_op.drop_column('sign')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('sign', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###
