"""comments table

Revision ID: cb7714d6afe5
Revises: 1630bf794dcd
Create Date: 2024-04-05 13:01:52.035769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7714d6afe5'
down_revision = '1630bf794dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name=op.f('fk_comments_media_id_medias')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    sa.UniqueConstraint('content', name=op.f('uq_comments_content'))
    )
    op.drop_table('commentss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentss',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('media_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], name='fk_commentss_media_id_medias'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_commentss_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_commentss'),
    sa.UniqueConstraint('content', name='uq_commentss_content')
    )
    op.drop_table('comments')
    # ### end Alembic commands ###
